import { Screen } from "@/components/Screen";
import { useAppDispatch } from "@/hooks/redux";
import { setPageType } from "@/redux/reducer/pageSlice";

export const PrivacyAndPolicy = () => {
  const dispatch = useAppDispatch();

  return (
    <Screen>
      <div className="text-[#043a66] text-left text-sm font-medium">
        <h1 className="text-2xl font-bold mb-4">Privacy Policy</h1>

        <p className="text-[13px] font-bold underline text-pink-700 mb-4">
          Read the privacy policy carefully before using this app. By clicking
          at the end of this policy where indicated, you are consenting to our
          collection and use of your information as described in this policy.
        </p>

        <p className="mb-4">
          This Privacy Policy describes how the{" "}
          <span className="font-semibold">Lung Cancer Screening</span> app
          collects, uses, shares and protects information that we collect from
          you online.
        </p>

        <ol className="list-decimal pl-4 space-y-3">
          <li>
            While using our website, we may ask you to provide us with certain
            information including health information that you provide when using
            the app. We may use this to determine whether you meet criteria for
            lung cancer screening. Submitting personal information is voluntary.
            Your contact information may also be recorded if you submit a
            contact request.
          </li>
          <li>
            <strong>"Web Analytics:"</strong> We use Google’s Universal
            Analytics (“UA”) to monitor Website usage and analyze aggregate
            demographic and interest data of our visitors. We will not use this
            information to identify you as an individual.
          </li>
          <li>
            We may disclose user level personal information (as well as data
            generated by cookies and non-personally identifying information we
            aggregate) to trusted services providers, affiliated organizations
            and contractors, who will use that information in order to process
            it on our behalf or to provide services related to the Website.
            Other than as described above and with the users, by using the
            Website, you consent to the transfer of such information to such
            parties.
          </li>
          <li>
            Security: While we take reasonable steps to protect private
            information, no security measures are completely foolproof, and we
            do not guarantee the security of the website or any time. We will
            not be liable for any breach of security measures on the website or
            loss, misuse, or alteration of information.
          </li>
        </ol>

        <button
          className="w-full bg-[#043a66] cursor-pointer text-white font-semibold text-sm px-4 py-3 mt-8 rounded-[12px]"
          onClick={() => dispatch(setPageType("FLOW_CHART"))}
        >
          I have read and understood this privacy policy and consent to its
          terms
        </button>
      </div>
    </Screen>
  );
};
